correct the format of dependencies  in Cargo.toml
The original format of `Cargo.toml` triggers a compilation error:
```shell
➜  ch8-mget  cargo build
error: failed to parse manifest at `/.../rust-in-action-src/ch8/ch8-mget/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  expected a table key, found a newline at line 10 column 12
```
my toolchain version:
```shell
stable-x86_64-unknown-linux-gnu (default)
rustc 1.57.0 (f1edd0429 2021-11-29)
```
After correction, it works all right:)